import Head from "next/head";
import Slider from "../components/common/Slider";
import { useSelector, useDispatch } from "react-redux";
import {
  openSlidingComponentState,
  openSlidingComponent,
} from "../redux/sliderSlice";
import LogIn from "../components/Home/LogIn";
import SignUp from "../components/Home/SignUp";

export default function Home() {
  const dispatch = useDispatch();
  const sliderState = useSelector(openSlidingComponentState);
  const sliderComponents = {
    "Sign up": <SignUp />,
    "Log in": <LogIn />,
  };
  const renderedComponent = sliderComponents[sliderState];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <ul className="flex">
          <button
            onClick={() => dispatch(openSlidingComponent("Log in"))}
            className="px-4"
          >
            Login
          </button>
          <button
            onClick={() => dispatch(openSlidingComponent("Sign up"))}
            className="px-4"
          >
            Sign up
          </button>
        </ul>
      </nav>
      <main>


      </main>
      <Slider>{renderedComponent}</Slider>
      {sliderState && (
        <div className="fixed opacity-60 bg-black inset-0 overflow-y-auto"></div>
      )}
      <footer>
 
      </footer>
    </div>
  );
}
