import Head from "next/head";
import Slider from "../components/common/Slider";
import { useSelector, useDispatch } from "react-redux";
import {
  openSlidingComponentState,
  openSlidingComponent,
} from "../redux/sliderSlice";
import LogIn from "../components/Home/LogIn";
import SignUp from "../components/Home/SignUp";
import Image from "next/image";
import HeroPic from "../public/hero.png";
import SignUpForSupplier from "../components/Home/SignUpForSupplier";

export default function Home() {
  const dispatch = useDispatch();
  const sliderState = useSelector(openSlidingComponentState);
  const sliderComponents = {
    "Sign up": <SignUp />,
    "Log in": <LogIn />,
    "Sign up for Supplier": <SignUpForSupplier />,
  };
  const renderedComponent = sliderComponents[sliderState];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="absolute z-10 bg-white border-solid border-primary border-b-4 w-full p-4 flex justify-between">
        <h1 className="text-primary text-2xl font-black">Growwcery</h1>
        <ul className="flex">
          <button
            onClick={() => dispatch(openSlidingComponent("Log in"))}
            className="px-4 hover:text-primary"
          >
            Login
          </button>
          <button
            onClick={() => dispatch(openSlidingComponent("Sign up"))}
            className="px-4  hover:text-primary"
          >
            Sign up
          </button>
          <button
            onClick={() =>
              dispatch(openSlidingComponent("Sign up for Supplier"))
            }
            className="px-4  hover:text-primary"
          >
            For suppliers
          </button>
        </ul>
      </nav>
      <main>
        <Image src={HeroPic} alt="Hero" layout="fill" />
      </main>
      <Slider>{renderedComponent}</Slider>
      {sliderState && (
        <div className="fixed opacity-60 bg-black inset-0 overflow-y-auto"></div>
      )}
      <footer></footer>
    </div>
  );
}
